### ISSUE TITLE
Two more to add

### ISSUE THREAD

**Issue by LinuxJedi** [dveeden/mysql-history-graph#3]
Two major forks if you want to track history I think are OurSQL and WebScaleSQL. I don't have enough data on either to fill the exact gaps precisely though, it would require research, likely in archive.org and maybe input from people such as Mark Callaghan.

**Comment by LinuxJedi** [comment]
Sorry, it was OurDelta, not OurSQL.

**Comment by dveeden** [comment]
Yes, would be good to get input from @arjenlentz, @mdcallag and @jeremycole on this.

**Comment by arjenlentz** [comment]
Hi Daniel, goeiemorgen.
You can find the history of OurDelta versions/releases and contents at https://launchpad.net/ourdelta

Quick summary:
It existed as a "distro" (not fork) of MySQL 5.0 and 5.1, adding core functionality and storage engines and producing decent Debian/Ubuntu builds as well as RPMs. Repos for all those were available.

We did the patches using quilt, an awesome patch tool that is used in various other places.

I did most of the patch stuff, and an engineer at my company Open Query (Peter Lieverdink, cafuego) did most of the build automation. We had a little KVM build farm for the different distros and versions.

The various patches were integrated in to MariaDB (which came along a few years later), and we gave our build system to Monty Program (for the DEB builds an the repos, specifically), so at that point OurDelta was no longer needed.
It served its purpose at the time.

**Comment by mdcallag** [comment]
I doubt WebScaleSQL ever ran in production anywhere. Intentions were good but maybe the teams from different companies were too busy to focus on it. I don't blame them.

**Comment by dveeden** [comment]
I've added WebScaleSQL. Not completely sure what to do with OurDelta as it seems to sit somewhere between packaging it (like Linux distros also do) and proper fork.
